### ISSUE TITLE
Really more of a question than an actual issue

### ISSUE THREAD

**Issue by pa-0** [uPaymeiFixit/online-marketplace-manager#1]
This is sweet.  How difficult would it be for an amateur coder somewhere between beginner / intermediate to port this so that it works for Windows? Thanks

**Comment by uPaymeiFixit** [comment]
This project doesn't work anymore, as each of these marketplaces have drastically changed their listing processes since I wrote it. 

But looking back at the project, even if it _did_ work it's not a great way to solve the problem. I would recommend looking into something like [Puppeteer](https://pptr.dev/), which will work on Windows out of the box.

**Comment by pa-0** [comment]
Thanks for this
